# .github/workflows/stale.yml
name: Close stale issues and PRs

on:
  schedule:
    # Run every day at 01:17 UTC (avoid :00 to reduce schedule contention)
    - cron: '17 1 * * *'
  workflow_dispatch: {}  # allow manual runs

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues and PRs
        # Tip: Pin to a full-length commit SHA in regulated environments
        uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'Stale'
          stale-pr-label: 'Stale'
          stale-issue-message: >
            This issue has been automatically marked as stale due to inactivity.
            It will be closed in 7 days unless there is further activity.
          stale-pr-message: >
            This pull request has been automatically marked as stale due to inactivity.
            It will be closed in 7 days unless there is further activity.
          close-issue-message: >
            Closing as stale. Please reopen if this is still relevant.
          close-pr-message: >
            Closing as stale. Please reopen if this is still relevant.
          operations-per-run: 30
